services:
  backend:
    build: ./backend
    environment:
      - GIPHY_TOKEN=${GIPHY_TOKEN}
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
